- type: department
  id: Civilian
  name: department-Civilian
  description: department-Civilian-description
  color: "#9FED58"
  weight: -10
  roles:
  - Chaplain
  - Lawyer

- type: department
  id: Medical
  name: department-Medical
  description: department-Medical-description
  color: "#52B4E9"
  roles:
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic

#TODO camera operator
#- type: department
#  id: Silicon
#  name: department-Silicon
#  description: department-Silicon-description
#  color: "#D381C9"
# roles:
# - StationAi

- type: department
  id: Prisoner
  name: department-Prisoner
  description: department-Prisoner-description
  color: "#a46d06"
  roles:
  - Inmate
  #TODO fresh blood/fish
  #TODO junkie

- type: department
  id: Guard
  name: department-Guard
  description: department-Guard-description
  color: "#107e8f"
  roles:
  - CorrectionalOfficer
  #TODO warden
  #TODO - cadet (find better name)
