- type: job
  id: CorrectionalOfficer
  name: job-name-correctional-officer
  description: job-description-correctional-officer
  playTimeTracker: JobCorrectionalOfficer
  canBeAntag: false
  startingGear: CorrectionalOfficerGear
  icon: JobIconWarden
  setPreference: true
  overrideConsoleVisibility: true
  access:
  - CO
  extendedAccess:
  - External
- type: startingGear
  id: CorrectionalOfficerGear
  equipment:
    id: GuardPDA
    jumpsuit: ClothingUniformJumpsuitSecBlue
    shoes: ClothingShoesColorBrown
    head: ClothingHeadHatCommandSoft
